version: "3"
services:
volumes:
  frontend:
    build: ./
    container_name: comics-ui-dpwfsrjs
    ports:
      - 8888:8888
    environment:
      PORT: 8888
      REACT_APP_API_COMICS: http://backend:8080
      REACT_APP_API_MOVIE_DB: https://api.themoviedb.org/3
      REACT_APP_API_MOVIE_DB_IMG: https://image.tmdb.org/t/p/w500
      REACT_APP_APIKEY_MOVIE_DB: 815158e35877de2d9b49bd1c31727638